INSERT INTO deal_products (deal_id, product_id, quantity, unit_price, discount_percent) VALUES
((SELECT deal_id FROM deals WHERE deal_name = 'Nexus Corp - Revenue Analytics Pro'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Nexus Corp - Pipeline Expansion'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 2, 8500.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'BluePeak - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 1, 15000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'BluePeak - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 1, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'BluePeak - Analytics Upgrade'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Orion - Healthcare Analytics'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 1, 11000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Orion - Data Integration'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 2, 4500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vertex - Enterprise Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vertex - Enterprise Suite'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 2, 8500.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vertex - Renewal Deal'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crestline - Media Analytics'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crestline - Marketing Suite'), (SELECT product_id FROM products WHERE product_name = 'Marketing Automation'), 1, 7000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Irongate - Logistics Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Irongate - Logistics Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 1, 4500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Irongate - Data Integration Pack'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 3, 4500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Sapphire - Analytics Pro'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Sapphire - Dashboard Add-on'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 1, 5000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Pinnacle - Health Revenue Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Pinnacle - Health Revenue Suite'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Pinnacle - Analytics Renewal'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Sterling - Finance Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Sterling - Forecast Engine'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 1, 15000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Redwood - Retail Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Redwood - Pipeline Manager'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 1, 8500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'CloudNine - Enterprise Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 4, 12000.00, 20.00),
((SELECT deal_id FROM deals WHERE deal_name = 'CloudNine - Enterprise Analytics'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 3, 8500.00, 20.00),
((SELECT deal_id FROM deals WHERE deal_name = 'CloudNine - Security Module'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 2, 6000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Amber - Consulting Suite'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 1, 9500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Amber - Dashboard License'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 1, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Titanium - Manufacturing Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Titanium - Manufacturing Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 2, 4500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Titanium - API License Expansion'), (SELECT product_id FROM products WHERE product_name = 'API Access License'), 3, 3500.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Horizon - Digital Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Horizon - Product Suite'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 1, 8500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Cascade - Energy Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Cascade - Forecast Engine'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 1, 15000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Falcon - Aerospace Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 4, 12000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Falcon - Aerospace Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 3, 11000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Falcon - Contract Renewal'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 4, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Quantum - Pharma Analytics Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Quantum - Clinical Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 3, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Stratos - Cloud Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Stratos - API Integration'), (SELECT product_id FROM products WHERE product_name = 'API Access License'), 2, 3500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Zenith - Finance Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Zenith - Finance Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Zenith - Risk Analytics Module'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 3, 6000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Cobalt - Manufacturing Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 3, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Cobalt - Operations Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Polaris - Partner Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Polaris - Revenue Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Atlas - Biotech Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Atlas - Research Analytics Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crown - Retail Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crown - Customer Analytics'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Blackstone - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 4, 12000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Blackstone - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 3, 15000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Blackstone - Risk Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 3, 6000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Helios - Tech Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 3, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Helios - Sales Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Neptune - Finance Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Neptune - Portfolio Analytics'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Helix - Biotech Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Helix - Lab Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Dawnlight - Health Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Dawnlight - Operations Analytics'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Ironbridge - Tech Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Ironbridge - Engineering Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Solaris - Energy Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Solaris - Grid Analytics Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 1, 11000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Harborview - Consulting Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Harborview - Business Analytics'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Axiom - Pharma Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 4, 12000.00, 15.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Axiom - Pharma Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Axiom - Clinical Analytics'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Voyager - Tech Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Voyager - Product Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 2, 8500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Lunar - Biotech Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Lunar - Research Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Ironclad - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Ironclad - Investment Analytics'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Summit - Energy Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Summit - Grid Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 1, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Citadel - Security Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 3, 6000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Citadel - Threat Analytics'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Granite - Systems Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Granite - Architecture Suite'), (SELECT product_id FROM products WHERE product_name = 'API Access License'), 2, 3500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Heritage - Finance Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Heritage - Wealth Analytics'), (SELECT product_id FROM products WHERE product_name = 'Sales Forecast Engine'), 2, 15000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Thunderbolt - Energy Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Thunderbolt - Grid Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 1, 12000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Keystone - Consulting Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Keystone - Strategy Analytics'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 2, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Compass - Finance Analytics'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Compass - Risk Dashboard'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 1, 6000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Pulse - Health Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Pulse - Clinical Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 1, 11000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Bridgewater - Logistics Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Bridgewater - Supply Chain Analytics'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 2, 4500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crescent - Media Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crescent - Content Analytics'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 1, 5000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vortex - Consulting Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vortex - Strategy Suite'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 1, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crestview - Finance Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crestview - Risk Analytics'), (SELECT product_id FROM products WHERE product_name = 'Advanced Security Module'), 1, 6000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Delphi - Strategy Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Oceanic - Logistics Suite'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 2, 8500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Prism - Healthcare Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 2, 9500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Starbridge - Tech Suite'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Starbridge - Engineering Analytics'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 1, 11000.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Nebula - Tech Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 2, 8500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Nebula - Product Suite'), (SELECT product_id FROM products WHERE product_name = 'Executive Dashboard'), 1, 5000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Nimbus - Network Intelligence'), (SELECT product_id FROM products WHERE product_name = 'API Access License'), 3, 3500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Firefly - Tech Suite'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 1, 8500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Mosaic - Marketing Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Marketing Automation'), 2, 7000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Bloom - Health Analytics'), (SELECT product_id FROM products WHERE product_name = 'Customer Success Suite'), 1, 9500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Emerald - Export Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 2, 4500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Apex - Retail Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Pipeline Manager'), 1, 8500.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Highpoint - Logistics Analytics'), (SELECT product_id FROM products WHERE product_name = 'Data Integration Pack'), 1, 4500.00, 0.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Meridian - Finance Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Vanguard - Media Intelligence Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Fortis - Manufacturing Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 3, 12000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Solaris Mfg - Operations Suite'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 3, 11000.00, 10.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Crimson - Finance Intelligence'), (SELECT product_id FROM products WHERE product_name = 'Revenue Analytics Pro'), 2, 12000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Equinox - Energy Analytics'), (SELECT product_id FROM products WHERE product_name = 'Deal Intelligence Hub'), 2, 11000.00, 5.00),
((SELECT deal_id FROM deals WHERE deal_name = 'Onboarding Package - Nexus Corp'), (SELECT product_id FROM products WHERE product_name = 'Onboarding Package'), 1, 3000.00, 0.00);
